pipeclient/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from account.views import (login_view, register_view, logout_view)
from rest_framework_jwt.views import obtain_jwt_token

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^pipeline/', include("pipeline.urls", namespace='pipelines')),
    url(r'^register/$', register_view, name='register'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/pipeline/', include("pipeline.api.urls", namespace='pipeline-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pipeline/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	pipeline_list,
	pipeline_create,
	pipeline_detail,
	pipeline_update,
	pipeline_delete,
	)

urlpatterns = [
	url(r'^$', pipeline_list, name='list'),
    url(r'^create/$', pipeline_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', pipeline_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', pipeline_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', pipeline_delete, name='delete'),
    #url(r'^Pipelines/$', "<appname>.views.<function_name>"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Pipeline Client</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <!-- chartist CSS -->
    <link href="{% static 'assets/plugins/chartist-js/dist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/chartist-js/dist/chartist-init.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css' %}" rel="stylesheet">
    <!--This page css - Morris CSS -->
    <link href="{% static 'assets/plugins/c3-master/c3.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'css/colors/blue.css' %}" id="theme" rel="stylesheet">
    {% block style %}

    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <b>Smart Pipeline</b>
                     </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item hidden-sm-down search-box"> <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search">
                                <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i class="ti-close"></i></a> </form>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <!-- ============================================================== -->
                        <!-- Profile -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user }}</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        {% block content %}

        {% endblock %}
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/plugins/bootstrap/js/tether.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!-- chartist chart -->
    <script src="{% static 'assets/plugins/chartist-js/dist/chartist.min.js' %}"></script>
    <script src="{% static 'assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js' %}"></script>
    <!--c3 JavaScript -->
    <script src="{% static 'assets/plugins/d3/d3.min.js' %}"></script>
    <script src="{% static 'assets/plugins/c3-master/c3.min.js' %}"></script>
    <!-- Chart JS -->
    <script src="{% static 'js/dashboard1.js' %}"></script>
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock %}
    
{% block content %}
<div class="row">
  <br>
  <img src="{% static 'img/home_logo.jpg' %}" class="rounded float-left m-4" alt="home logo" width="40%" height="40%">
  <div class="col-md-5">
    <br>
    <form method='POST' action="." enctype='multipart/form-data' class="form-signin">{% csrf_token %}
      <img class="mb-4" src="{% static 'img/crypt_logo.jpg' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      {{ form.errors }}
      <label for="inputEmail" class="sr-only">Username</label>
      <!-- <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus> -->
      {{ form.username }}
      <br>
      <br>
      <label for="inputPassword" class="sr-only">Password</label>
      {{ form.password }}
      
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <a href="{% url 'register' %}">Create an account...here</a>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <!-- <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p> -->
    </form>
  </div>
</div>
    
{% endblock %}

templates/pages-error-404.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
    <title>Material Pro Admin Template - The Most Complete & Trusted Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header card-no-border">
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper" class="error-page">
        <div class="error-box">
            <div class="error-body text-center">
                <h1>404</h1>
                <h3 class="text-uppercase">Page Not Found !</h3>
                <p class="text-muted m-t-30 m-b-30">YOU SEEM TO BE TRYING TO FIND HIS WAY HOME</p>
                <a href="index.html" class="btn btn-info btn-rounded waves-effect waves-light m-b-40">Back to home</a> </div>
            <footer class="footer text-center">© 2017 Material Pro.</footer>
        </div>
    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="assets/plugins/bootstrap/js/tether.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!--Wave Effects -->
    <script src="js/waves.js"></script>
</body>

</html>

templates/pipeline_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    {% include 'sidebar.html' %}
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 col-8 align-self-center">
                    <h3 class="text-themecolor">Dashboard</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <div class="row">
                    <!-- column -->
                    <div class="col-lg-12">
                        <div class="card">
                          <div class="card-block">
                            <div class="col-sm-6 offset-3">
                              <form method='POST' action="." enctype='multipart/form-data' class="form-signin">{% csrf_token %}             
                                <div class="text-center mb-4">
                                  <img class="mb-4" src="{% static 'img/logo1.jpg' %}" alt="" width="72" height="72">
                                  <h1 class="h3 mb-3 font-weight-normal">Pipelines</h1>
                                  <p>Install a new pipeline by providing the necessary details below.</p>
                                </div>
                                

                                <div class="form-label-group">
                                  <!-- <input type="text" id="inputName" class="form-control" placeholder="Pipeline Name" required autofocus> -->
                                  {{ form.name }}
                                  {% if form.name.errors %}
                                    <div class="alert alert-danger" role="alert">
                                      {{ form.name.errors }}
                                    </div>
                                  {% endif %}
                                  <label for="inputName">Name</label>
                                </div>
                                <div class="form-label-group">
                                  {{ form.longitude }}
                                  {% if form.longitude.errors %}
                                    <div class="alert alert-danger" role="alert">
                                      {{ form.longitude.errors }}
                                    </div>
                                  {% endif %}
                                  <label for="inputLongitude">Longitude</label>
                                </div>
                                <div class="form-label-group">
                                  {{ form.latitude }}
                                  {% if form.latitude.errors %}
                                    <div class="alert alert-danger" role="alert">
                                      {{ form.latitude.errors }}
                                    </div>
                                  {% endif %}
                                  <label for="inputLatitude">Latitude</label>
                                </div>
                                <div class="custom-file">
                                  {{ form.image }}
                                  {% if form.image.errors %}
                                    <div class="alert alert-danger" role="alert">
                                      {{ form.image.errors }}
                                    </div>
                                  {% endif %}
                                </div>
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
                                <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p>
                              </form>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
        </div>
        
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->

{% endblock %}

templates/pipeline_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    {% include 'sidebar.html' %}
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 col-8 align-self-center">
                    <h3 class="text-themecolor">Pipeline Detail</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
                <div class="col-md-7 col-4 align-self-center">
                    <a href="{% url 'pipelines:create' %}" class="btn waves-effect waves-light btn-primary pull-right hidden-sm-down">Install New Pipeline</a>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <!-- Column -->
                <div class="col-lg-4 col-xlg-3 col-md-5">
                    <div class="card">
                        <div class="card-block">
                            <center class="m-t-30"> <img src="{{instance.image.url}}" class="img-circle" width="150" />
                                <h4 class="card-title m-t-10">{{ instance.name }}</h4>
                                <h6 class="card-subtitle">Accoubts Manager Amix corp</h6>
                                <div class="row text-center justify-content-md-center">
                                    <div class="col-4"><a href="javascript:void(0)" class="link"><i class="mdi mdi-hospital"></i>Damage status <font class="font-medium">{{ instance.is_damaged }}</font></a></div>
                                    <div class="col-4"><a href="javascript:void(0)" class="link"><i class="mdi mdi-hospital-marker"></i>Damage Level <font class="font-medium">{{ instance.damage_grade }}</font></a></div>
                                </div>
                                <div class="text-center m-t-30">
                                    <a href="{% url 'pipelines:delete' instance.slug %}" class="btn waves-effect waves-light btn-danger hidden-md-down">Delete</a>
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
                <div class="col-lg-8 col-xlg-9 col-md-7">
                    <div class="card">
                        <div class="card-block">
                            <form method='POST' action="." enctype='multipart/form-data' class="form-horizontal form-material">{% csrf_token %}
                                <div class="form-group">
                                    <label class="col-md-12">Pipe Name</label>
                                    <div class="col-md-12">
                                        {{ form.name }}
                                        <!-- <input type="text" placeholder="lokoja_pipeline" class="form-control form-control-line"> -->
                                    </div>
                                    {% if form.name.errors %}
                                        <div class="alert alert-danger" role="alert">
                                          {{ form.name.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Longitude</label>
                                    <div class="col-md-12">
                                        {{ form.longitude }}
                                       <!--  <input type="text" placeholder="-94.420307" class="form-control form-control-line"> -->
                                    </div>
                                    {% if form.longitude.errors %}
                                        <div class="alert alert-danger" role="alert">
                                          {{ form.longitude.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Latitude</label>
                                    <div class="col-md-12">
                                        {{ form.latitude }}
                                    </div>
                                    {% if form.latitude.errors %}
                                        <div class="alert alert-danger" role="alert">
                                          {{ form.latitude.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Damage status</label>
                                    <div class="col-md-12">
                                        {% for radio in form.is_damaged %}
                                            {{ radio.tag }}
                                            <label class="form-check-label" for="{{ radio.id_for_label }}">
                                                {{ radio.choice_label }}
                                            </label>
                                        {% endfor %}
                                    </div>
                                    {% if form.is_damaged.errors %}
                                        <div class="alert alert-danger" role="alert">
                                          {{ form.is_damaged.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Select Damage Level</label>
                                    <div class="col-sm-12">
                                        {{ form.damage_grade }}
                                    </div>
                                    {% if form.damage_grade.errors %}
                                        <div class="alert alert-danger" role="alert">
                                          {{ form.damage_grade.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                                
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>
            <!-- Row -->
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->

        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <!-- <footer class="footer"> © 2017 Material Pro Admin by wrappixel.com </footer> -->
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->

{% endblock %}

templates/sidebar.html
<aside class="left-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li> <a class="waves-effect waves-dark" href="{% url 'home' %}" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard</span></a>
                    </li>
                    <li> <a class="waves-effect waves-dark" href="pages-profile.html" aria-expanded="false"><i class="mdi mdi-account-check"></i><span class="hide-menu">Profile</span></a>
                    </li>
                    <li> <a class="waves-effect waves-dark" href="{% url 'pipelines:create' %}" aria-expanded="false"><i class="mdi mdi-creation"></i><span class="hide-menu">New Pipeline</span></a>
                    </li>
                    <li> <a class="waves-effect waves-dark" href="{% url 'pipelines:list' %}" aria-expanded="false"><i class="mdi mdi-table"></i><span class="hide-menu">Pipelines</span></a>
                    </li>
                    <li> <a class="waves-effect waves-dark" href="map-google.html" aria-expanded="false"><i class="mdi mdi-earth"></i><span class="hide-menu">Google Map</span></a>
                    </li>
                    
                    <li> <a class="waves-effect waves-dark" href="pages-error-404.html" aria-expanded="false"><i class="mdi mdi-help-circle"></i><span class="hide-menu">Error 404</span></a>
                    </li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
        <!-- Bottom points-->
        <div class="sidebar-footer">
            <!-- item--><a href="" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
            <!-- item--><a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
            <!-- item--><a href="{% url 'logout' %}" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a> </div>
        <!-- End Bottom points-->
    </aside>